### ISSUE TITLE
Generate Dataset for UAlberta Checklist

### ISSUE THREAD

**Issue by umesh-timalsina** [symbench/symbench-athens-client#63]
- [x] FDMExecutor (Added by #61)
- [x] Fixed Bemp Designs (Added by #61)
- [x] Ground Truth Testing (Should be added)
- [x] Interval Sampling method (Added by #61) 
- [ ] Interferences calculations (See #71)

**Comment by umesh-timalsina** [comment]
See #80 for docker related stuff. 
However, at a very high level, the API should look something like:

```py
from symbench_athens_client.experiments import ExperimentOnQuadCopterWithFixedBemp
ExperimentOnQuadCopterWithFixedBemp.run_for(lengths={}, flight_parameters={})
```
